FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copiar requirements desde la raíz
COPY ../requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copiar el script de ingesta
COPY ingesta/ingesta.py .

EXPOSE 8000
CMD ["python", "ingesta.py"]
