FROM python:3.11-slim

WORKDIR /app

COPY . .

ENTRYPOINT ["python", "main.py"]

# Link a la imagen docker generada y subida a Docker Hub: 
# https://hub.docker.com/layers/celiiasarrio/entregable/latest/images/sha256-f9cf594980c356abfdc9c2ef32a21e6752d08200d407fc968e1e874b5e644fe2
