# Dockerfile para dashboard Plotly/Dash
FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

# Copiar requirements desde la raíz
COPY ../requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copiar código de la app desde la carpeta visualizacion
COPY visualizacion/app_plotly.py .

EXPOSE 8050

CMD ["python", "app_plotly.py"]
