#Imagen base con Python
FROM python:3.12-slim

#Directorio de trabajo dentro del contenedor
WORKDIR /app

#Copiamos SOLO requirements para aprovechar cache
COPY requirements.txt .

#Instalamos dependencias
RUN pip install --no-cache-dir -r requirements.txt

#El código NO se copia aquí (vendrá por volumen)
CMD ["python", "valenbisi_collector.py"]
