#Dockerfile para construir el contenedor de las apis
FROM python:3.14-slim
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 5000
CMD ["python", "valenbisi_collector.py"]