services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    volumes:
      - postgresDB:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: unless-stopped

  app:
    image: python:3.11
    working_dir: /app
    volumes:
      - ./:/app                # Código fuente
      - python_cache:/root/.cache/pip  # Cache persistente de pip
    env_file:
      - .env
    command: >
      sh -c "pip install -r requirements.txt && python main.py"
    depends_on:
      - db
    restart: "no"

volumes:
  postgresDB:
  python_cache: