FROM python:3.14

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD rm requirements.txt

COPY inverterMessages.py .

ENTRYPOINT [ "python", "inverterMessages.py" ]
