services:
  db:
    image: postgres:17-alpine
    container_name: postgres_container
    env_file:
      - .env-db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  ahorcado:
    build: .
    container_name: ahorcado_container
    env_file:
      - .env-db
    environment:
      GETWORDFROMAPI: 'True'
    command: python ahorcado.py palabras.txt
    volumes:
      - ./:/app
    depends_on:
      - db
