version: 2

models:
  - name: stg_ventas
    description: "Ventas limpias y casteadas"
    columns:
      - name: ticket_id
        description: "Clave primaria del ticket"
        tests:
          - not_null  # ¡No puede haber ventas sin ID!
          
      - name: cantidad
        tests:
          - not_null

  - name: stg_articulos
    columns:
      - name: articulo_id
        tests:
          - unique    # ¡No puede haber dos artículos con el mismo ID!
          - not_null
      - name: gama
        tests:
          - accepted_values: # Solo permitimos estos valores exactos
              values: ['Alta', 'Media', 'Baja']

  - name: stg_clientes
    columns:
      - name: cliente_id
        tests:
          - unique
          - not_null