services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    volumes:
      - postgresDB:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ahorcado:latest
    working_dir: /app            
    env_file: .env
    depends_on:
      - db  
volumes:
    postgresDB: