services: 
   #Productor de kafka, fozamos el build desde aqui para hacer mas facil el desarrollo.
producer: 
     #Este comando busca el dockerfile en el directorio de ejecución y construye la imagen a partir de él para el contenedor.
     #Es tal cual lo que haríamos nosotros con el docker build . -t nombre_imagen, que posteriormente pasaríamos esa imagen al compose
     build: .
     container_name: producer
     workdir: /app
     depens on:
       -kafka
     command: python producer.py


   #Primer consumidor de kafka, fozamos el build desde aqui para hacer mas facil el desarrollo
consumer: 
     #Este comando busca el dockerfile en el directorio de ejecución y construye la imagen a partir de él para el contenedor.
     build: .
     container_name: consumer
     workdir: /app
     depens on:
       -kafka
     command: python consumer.py

#Creamos un contenedor de zookeper, el orquestador de clusters de kafka (el jefe de los brokers xd)
zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

#Creamos el propio contenedor del servicio de kafka, que recibe los mensajes y los envia a los suscriptores
#Depende completamente de que zookeper (el jefe) esté levantado
kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
