#Creamos una imagen a partir de python 3:13 slim y la llamamos BASE
FROM python:3.13-slim AS BASE

#Creamos en el contenedor la carpeta /APP donde se guardará todo lo que definamos en el dockerfile como .
WORKDIR /app

#Copiamos el archivo requirements.txt de la carpeta de ejecución (debemos ejecutar desde la raiz del dockerfile) a la carpeta /app del contenedor
COPY requirements.txt .

#Con el archivo de requierimientos copiado, instalamos las librerías 
RUN pip install -r requirements.txt

#Copiamos el contenido que queramos ejecutar en /app del contenedor, solo estos 3 ejecutables
COPY consumer.py .
COPY producer.py .
COPY init.sql .

