CREATE DATABASE myFirstDB;
CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    email           VARCHAR(255) UNIQUE NOT NULL,
    password      TEXT NOT NULL,
    register_date   TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE users ADD COLUMN age VARCHAR(3);

ALTER TABLE users ALTER COLUMN age TYPE INTEGER USING age::integer;


CREATE TABLE IF NOT EXISTS employees (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  birth_date DATE,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL
);

ALTER TABLE employees
ADD COLUMN salary NUMERIC(10,2),
ADD COLUMN title VARCHAR(100),
ADD COLUMN title_date DATE;

INSERT INTO users (first_name, last_name, email, password, age)
VALUES ('Ada', 'Lovelace', 'ada@example.com', '123456', 36);

INSERT INTO users (first_name, last_name, email, password,age) 
VALUES ('Luffy', 'Monkey D.', 'luffy@mugiwara.com', '123456',17), 
('Zoro', 'Roronoa', 'zoro@mugiwara.com', '123456',21),
('Sanji', 'Vinsmoke', 'sanji@mugiwara.com', '123456',22);

SELECT * FROM users;

SELECT first_name, email FROM users;

SELECT * FROM users WHERE age=19;

INSERT INTO employees (birth_date, first_name, last_name, salary, title, title_date)
VALUES
('1985-04-12','Carlos','Pérez', 12000.50, 'Analista', '2020-03-15'),
('1990-07-23','Carlos','Gómez', 18000.00, 'Desarrollador', '2021-06-10'),
('1992-11-05','Carlos','Ramírez', 25000.75, 'Líder de Proyecto', '2022-01-20'),

('1988-05-10','Ana','Martínez', 15000.00, 'QA Engineer', '2020-08-30'),
('1991-12-20','Lucía','Fernández', 22000.25, 'Data Analyst', '2020-09-10'),
('1987-03-15','Miguel','Torres', 35000.00, 'Project Manager', '2021-02-18'),
('1993-08-08','Laura','Sánchez', 18000.00, 'UX Designer', '2020-11-25'),
('1995-09-12','David','López', 27000.50, 'Backend Developer', '2022-05-01'),
('1989-01-30','Sofía','González', 31000.00, 'Frontend Developer', '2021-07-22'),
('1994-06-18','Andrés','Ramírez', 5000.00, 'Intern', '2023-03-15'),
('1990-02-05','María','Vega', 48000.00, 'CTO', '2022-09-01'),
('1986-12-11','Javier','Ruiz', 42000.50, 'DevOps Engineer', '2020-12-12'),
('1992-07-07','Isabel','Ortiz', 33000.75, 'Marketing Specialist', '2021-05-20'),
('1988-09-09','Fernando','Castro', 15000.00, 'Support Engineer', '2023-01-15'),
('1991-10-21','Patricia','Jiménez', 20000.25, 'HR Manager', '2022-11-30');

SELECT * FROM employees;

SELECT first_name, salary FROM employees;

SELECT * 
FROM employees
WHERE id = 2

SELECT * 
FROM employees
WHERE salary > 20000;

SELECT * 
FROM employees
WHERE salary > 20000;

SELECT * 
FROM employees
WHERE salary <= 10000;

SELECT * FROM users WHERE id = 2;

DELETE FROM users WHERE id = 7;

UPDATE employees
SET first_name = 'Pedro'
WHERE id = 7;

DELETE FROM employees
WHERE id = 5;

DELETE FROM employees
WHERE salary > 20000;

SELECT * FROM employees WHERE salary > 20000;

SELECT * 
FROM employees
WHERE salary BETWEEN 14000 AND 50000;

SELECT * 
FROM employees
ORDER BY birth_date DESC;

SELECT * FROM employees;

SELECT first_name || ' ' || last_name AS name FROM users;

SELECT DISTINCT age FROM users;

SELECT * FROM users WHERE last_name LIKE '%a%';
SELECT * FROM users WHERE first_name LIKE 'S%';
SELECT * FROM users WHERE first_name LIKE '%o';
SELECT * FROM users WHERE last_name NOT LIKE '%r%';

/* Práctica pág 50*/

SELECT DISTINCT first_name
FROM employees;

SELECT first_name || ' ' || last_name AS nombre_completo
FROM employees
WHERE id = 9;


SELECT *
FROM employees
WHERE first_name LIKE 'P%';

SELECT *
FROM employees
WHERE first_name ILIKE '%a%';

SELECT COUNT(id) FROM users;

SELECT age, COUNT(age) FROM users GROUP BY age;


/*Ejercicio pag 54*/

SELECT COUNT(*) AS total_empleados
FROM employees;

SELECT *
FROM employees
ORDER BY salary DESC
LIMIT 1;

SELECT title, AVG(salary) AS salario_medio
FROM employees
GROUP BY title;


SELECT 
  title,
  MAX(salary) AS salario_maximo,
  MIN(salary) AS salario_minimo
FROM employees
GROUP BY title;

/* Calcular valores con columnas numéricas*/

SELECT first_name, age, age + 5 AS age_in_5_years
FROM users;


/*Añadimos una columna de salario*/

ALTER TABLE users ADD COLUMN salary NUMERIC(10,2);

--Ponemos algunos valores de ejemplo

UPDATE users
SET salary = CASE id
WHEN 7 THEN 1234.10
WHEN 8 THEN 1500.50
WHEN 11 THEN 900.00
ELSE 1100.75
END;

SELECT * FROM users;


SELECT first_name, salary,
salary * 0.12 AS ahorro_mensual
FROM users;

SELECT first_name, salary,
salary * 0.12 AS ahorro_mensual,
ROUND((salary * 0.12) * 3, 2) AS total_ahorrado_aproximado
FROM users;

-- Práctica pág 60
SELECT 
  first_name,
  ROUND(salary, 2) AS salario_redondeado
FROM employees;


CREATE TABLE departments (
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(100) NOT NULL
);

INSERT INTO departments(name)
VALUES ('Engineering');

INSERT INTO departments(name)
VALUES ('Marketing');

SELECT * FROM departments;

ALTER TABLE employees
ADD COLUMN department_id INTEGER,
ADD CONSTRAINT fk_department
FOREIGN KEY (department_id)
REFERENCES departments(id);


UPDATE employees
SET department_id = 1
WHERE id IN (1, 2);

UPDATE employees
SET department_id = 2
WHERE id = 4;

SELECT * FROM employees;

SELECT 
  e.first_name,
  d.name 
FROM employees AS e
INNER JOIN departments AS d 
ON e.department_id = d.id;









