services:
  dbt:
    build: .
    image: dbt-duckdb-setup
    container_name: dbt_init_container
    volumes:
      - .:/usr/app
    working_dir: /usr/app/Jorge_DBT
    ports:
      - "8080:8080"
    environment:
      - PYTHONDONTWRITEBYTECODE=1