# ./dbt/dockerfile.dbt
FROM python:3.11-slim

WORKDIR /app

# Copiar requirements.txt desde la raíz
COPY ../requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt
COPY . .

CMD ["dbt", "run", "--profiles-dir", "."]
