#version: '3.8' no es necesario

services:
  db:
    image: postgres:14-alpine
    container_name: ahorcado_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ahorcado_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  app:
    build: .
    container_name: ahorcado_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ahorcado_db
      DB_USER: user
      DB_PASSWORD: password
    
  
    command: >
      /bin/sh -c "
      # 1. Espera a que la base de datos este lita
      echo 'Esperando 25 segundos, no 15, ya que por algun motivo se enfada el programa porque no el doy el tiempo suficienote a la DB...';
      sleep 25; 
      
      # 2. Reemplaza la shell actual con el  de Python (exec). 
      
      echo 'Iniciando el script ahorcado.py en modo persistente...';
      exec python ahorcado.py
      "
volumes:
  postgres_data:
