# version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: ahorcado_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ahorcado_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  app:
    build: .
    container_name: ahorcado_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ahorcado_db
      DB_USER: user
      DB_PASSWORD: password
    command: >
      /bin/sh -c "
      sleep 15; 
      python ahorcado.py palabras.txt; 
      echo ''; 
      echo ' CONTENIDO DE LA TABLA RESULTADOS '; 
      psql -h db -U user -d ahorcado_db -c 'SELECT palabra, intentos, letras_acertadas, letras_falladas FROM resultados ORDER BY palabra, intentos LIMIT 20;'; 
      "
#esto esta medio mal porque intento automatizarlo y aun buscando con ia y demas no me ha salido asi que lo he dejado sin más
volumes:
  postgres_data: