version: '3.8'

services:
  api:
    build: .
    container_name: flask_twitter_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    restart: always