FROM python:3.12-slim 

WORKDIR /app

COPY api.py .
COPY requirements.txt .

RUN apt-get update && apt-get install -y curl
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "api.py"]