services:
  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile.api
    image: api:latest
    ports:
      - "5000:5000"
    env_file:
      - .env

  consumir_api:
    container_name: consumir_api
    build: 
      context: .
      dockerfile: Dockerfile.consumir_api
    image: consumir_api:latest