services:
  # Servicio de la Base de Datos PostgreSQL
  db:
    image: postgres:17-alpine 
    env_file:
      - .env
    volumes:
      - postgresDB:/var/lib/postgresql/data
    ports:
      - "5433:5432" 
    restart: unless-stopped
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Servicio de la Aplicación Python (El Ahorcado)
  app:
    build: . 
    image: ahorcado_final
    working_dir: /app
    env_file: .env
    command: palabras.txt 
    depends_on:
      db:
        condition: service_healthy 

volumes:
  postgresDB: