services:
  db_valenbisi:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresDB_valenbisi:/var/lib/postgresql/data
    ports:
      - "5432:5432"  
    restart: unless-stopped
  app:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    env_file: .env
    command: >
      sh -c " pip install -r requirements.txt && python -u valenbisi_collector.py "
    depends_on:
      - db_valenbisi
  
  dbt:
    build: .
    container_name: dbt-valenbisi
    volumes:
      - ./:/usr/app/dbt
      - ./profiles.yml:/root/.dbt/profiles.yml
    environment:
      - DBT_PROFILES_DIR=/usr/app/dbt
    working_dir: /usr/app/dbt/dbt_valenbisi
    entrypoint: ["/bin/bash"]
    tty: true
    depends_on:
      - db_valenbisi


volumes:
  postgresDB:
  postgresDB_valenbisi:
