FROM python:3.11-slim
WORKDIR /app

COPY valenbisi_collector.py .
COPY funciones.py .
COPY requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt

CMD ["python","valenbisi_collector.py"]