CREATE TABLE IF NOT EXISTS ahorcado (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PALABRA VARCHAR(100) NOT NULL,
    LETRAS_ACERTADAS VARCHAR(100) NOT NULL,
    FALLADAS VARCHAR(100) NOT NULL,
    INTENTOS NUMERIC(1000,0),
    TIEMPO DATE DEFAULT now()
);

SELECT * FROM ahorcado;

SELECT * FROM ahorcado_sinIA_API;

TRUNCATE TABLE ahorcado_sinIA_API;