apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: PostgreSQL
    url: db:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: valenbisi_db
      sslmode: 'disable'
      postgresVersion: 1700
      timescaledb: false