# Info examples for Jacinto's F1 dataset (2024 season)
# Equivalencia con el ejercicio del aeródromo:
#   airplanes  -> teams      (el "activo" que se gestiona)
#   passengers -> drivers    (las personas)
#   flights    -> races      (el evento con lista de participantes)
#   passengerIds [(id, status)] -> results [(driverId, gridPosition, finalPosition, points, status)]

teams = [
    {
        "teamId": "T-01",
        "name": "Red Bull Racing",
        "base": "Milton Keynes, UK",
        "teamPrincipal": "Christian Horner",
        "powerUnit": "Honda RBPT",
        "foundedYear": 2005,
        "championships": 6,
    },
    {
        "teamId": "T-02",
        "name": "Ferrari",
        "base": "Maranello, Italy",
        "teamPrincipal": "Frédéric Vasseur",
        "powerUnit": "Ferrari",
        "foundedYear": 1950,
        "championships": 16,
    },
    {
        "teamId": "T-03",
        "name": "Mercedes",
        "base": "Brackley, UK",
        "teamPrincipal": "Toto Wolff",
        "powerUnit": "Mercedes",
        "foundedYear": 2010,
        "championships": 8,
    },
    {
        "teamId": "T-04",
        "name": "McLaren",
        "base": "Woking, UK",
        "teamPrincipal": "Andrea Stella",
        "powerUnit": "Mercedes",
        "foundedYear": 1966,
        "championships": 8,
    },
    {
        "teamId": "T-05",
        "name": "Aston Martin",
        "base": "Silverstone, UK",
        "teamPrincipal": "Mike Krack",
        "powerUnit": "Mercedes",
        "foundedYear": 2021,
        "championships": 0,
    },
    {
        "teamId": "T-06",
        "name": "Alpine",
        "base": "Enstone, UK",
        "teamPrincipal": "Oliver Oakes",
        "powerUnit": "Renault",
        "foundedYear": 2021,
        "championships": 0,
    },
    {
        "teamId": "T-07",
        "name": "Williams",
        "base": "Grove, UK",
        "teamPrincipal": "James Vowles",
        "powerUnit": "Mercedes",
        "foundedYear": 1977,
        "championships": 9,
    },
    {
        "teamId": "T-08",
        "name": "RB",
        "base": "Faenza, Italy",
        "teamPrincipal": "Laurent Mekies",
        "powerUnit": "Honda RBPT",
        "foundedYear": 2024,
        "championships": 0,
    },
    {
        "teamId": "T-09",
        "name": "Kick Sauber",
        "base": "Hinwil, Switzerland",
        "teamPrincipal": "Alessandro Alunni Bravi",
        "powerUnit": "Ferrari",
        "foundedYear": 1993,
        "championships": 0,
    },
    {
        "teamId": "T-10",
        "name": "Haas",
        "base": "Kannapolis, USA",
        "teamPrincipal": "Ayao Komatsu",
        "powerUnit": "Ferrari",
        "foundedYear": 2016,
        "championships": 0,
    },
]


drivers = [
    {
        "driverId": "D-01",
        "code": "VER",
        "name": "Max Verstappen",
        "nationality": "Dutch",
        "dateOfBirth": "1997-09-30",
        "permanentNumber": 1,
        "teamId": "T-01",
    },
    {
        "driverId": "D-02",
        "code": "PER",
        "name": "Sergio Pérez",
        "nationality": "Mexican",
        "dateOfBirth": "1990-01-26",
        "permanentNumber": 11,
        "teamId": "T-01",
    },
    {
        "driverId": "D-03",
        "code": "LEC",
        "name": "Charles Leclerc",
        "nationality": "Monégasque",
        "dateOfBirth": "1997-10-16",
        "permanentNumber": 16,
        "teamId": "T-02",
    },
    {
        "driverId": "D-04",
        "code": "SAI",
        "name": "Carlos Sainz",
        "nationality": "Spanish",
        "dateOfBirth": "1994-09-01",
        "permanentNumber": 55,
        "teamId": "T-02",
    },
    {
        "driverId": "D-05",
        "code": "HAM",
        "name": "Lewis Hamilton",
        "nationality": "British",
        "dateOfBirth": "1985-01-07",
        "permanentNumber": 44,
        "teamId": "T-03",
    },
    {
        "driverId": "D-06",
        "code": "RUS",
        "name": "George Russell",
        "nationality": "British",
        "dateOfBirth": "1998-02-15",
        "permanentNumber": 63,
        "teamId": "T-03",
    },
    {
        "driverId": "D-07",
        "code": "NOR",
        "name": "Lando Norris",
        "nationality": "British",
        "dateOfBirth": "1999-11-13",
        "permanentNumber": 4,
        "teamId": "T-04",
    },
    {
        "driverId": "D-08",
        "code": "PIA",
        "name": "Oscar Piastri",
        "nationality": "Australian",
        "dateOfBirth": "2001-04-06",
        "permanentNumber": 81,
        "teamId": "T-04",
    },
    {
        "driverId": "D-09",
        "code": "ALO",
        "name": "Fernando Alonso",
        "nationality": "Spanish",
        "dateOfBirth": "1981-07-29",
        "permanentNumber": 14,
        "teamId": "T-05",
    },
    {
        "driverId": "D-10",
        "code": "STR",
        "name": "Lance Stroll",
        "nationality": "Canadian",
        "dateOfBirth": "1998-10-29",
        "permanentNumber": 18,
        "teamId": "T-05",
    },
    {
        "driverId": "D-11",
        "code": "GAS",
        "name": "Pierre Gasly",
        "nationality": "French",
        "dateOfBirth": "1996-02-07",
        "permanentNumber": 10,
        "teamId": "T-06",
    },
    {
        "driverId": "D-12",
        "code": "OCO",
        "name": "Esteban Ocon",
        "nationality": "French",
        "dateOfBirth": "1996-09-17",
        "permanentNumber": 31,
        "teamId": "T-06",
    },
    {
        "driverId": "D-13",
        "code": "ALB",
        "name": "Alexander Albon",
        "nationality": "Thai",
        "dateOfBirth": "1996-03-23",
        "permanentNumber": 23,
        "teamId": "T-07",
    },
    {
        "driverId": "D-14",
        "code": "SAR",
        "name": "Logan Sargeant",
        "nationality": "American",
        "dateOfBirth": "2000-12-31",
        "permanentNumber": 2,
        "teamId": "T-07",
    },
    {
        "driverId": "D-15",
        "code": "TSU",
        "name": "Yuki Tsunoda",
        "nationality": "Japanese",
        "dateOfBirth": "2000-05-11",
        "permanentNumber": 22,
        "teamId": "T-08",
    },
    {
        "driverId": "D-16",
        "code": "RIC",
        "name": "Daniel Ricciardo",
        "nationality": "Australian",
        "dateOfBirth": "1989-07-01",
        "permanentNumber": 3,
        "teamId": "T-08",
    },
    {
        "driverId": "D-17",
        "code": "BOT",
        "name": "Valtteri Bottas",
        "nationality": "Finnish",
        "dateOfBirth": "1989-08-28",
        "permanentNumber": 77,
        "teamId": "T-09",
    },
    {
        "driverId": "D-18",
        "code": "ZHO",
        "name": "Zhou Guanyu",
        "nationality": "Chinese",
        "dateOfBirth": "1999-05-30",
        "permanentNumber": 24,
        "teamId": "T-09",
    },
    {
        "driverId": "D-19",
        "code": "MAG",
        "name": "Kevin Magnussen",
        "nationality": "Danish",
        "dateOfBirth": "1992-10-05",
        "permanentNumber": 20,
        "teamId": "T-10",
    },
    {
        "driverId": "D-20",
        "code": "HUL",
        "name": "Nico Hülkenberg",
        "nationality": "German",
        "dateOfBirth": "1987-08-19",
        "permanentNumber": 27,
        "teamId": "T-10",
    },
]


# results: (driverId, gridPosition, finalPosition, points, status)
races = [
    {
        "raceId": "R-2024-01",
        "name": "Bahrain Grand Prix",
        "circuit": "Bahrain International Circuit",
        "country": "Bahrain",
        "date": "2024-03-02",
        "season": 2024,
        "round": 1,
        "laps": 57,
        "results": [
            ("D-01", 1, 1, 26, "Finished"),
            ("D-02", 5, 2, 18, "Finished"),
            ("D-04", 4, 3, 15, "Finished"),
            ("D-03", 2, 4, 12, "Finished"),
            ("D-06", 3, 5, 10, "Finished"),
            ("D-07", 7, 6, 8, "Finished"),
            ("D-05", 9, 7, 6, "Finished"),
            ("D-08", 8, 8, 4, "Finished"),
            ("D-09", 6, 9, 2, "Finished"),
            ("D-10", 10, 10, 1, "Finished"),
        ],
    },
    {
        "raceId": "R-2024-02",
        "name": "Saudi Arabian Grand Prix",
        "circuit": "Jeddah Corniche Circuit",
        "country": "Saudi Arabia",
        "date": "2024-03-09",
        "season": 2024,
        "round": 2,
        "laps": 50,
        "results": [
            ("D-01", 1, 1, 26, "Finished"),
            ("D-02", 3, 2, 18, "Finished"),
            ("D-03", 2, 3, 15, "Finished"),
            ("D-08", 6, 4, 12, "Finished"),
            ("D-09", 4, 5, 10, "Finished"),
            ("D-06", 7, 6, 8, "Finished"),
            ("D-20", 9, 7, 6, "Finished"),
            ("D-07", 8, 8, 4, "Finished"),
            ("D-13", 11, 9, 2, "Finished"),
            ("D-15", 10, 10, 1, "Finished"),
            ("D-04", 0, 0, 0, "DNS"),
        ],
    },
    {
        "raceId": "R-2024-03",
        "name": "Australian Grand Prix",
        "circuit": "Albert Park Circuit",
        "country": "Australia",
        "date": "2024-03-24",
        "season": 2024,
        "round": 3,
        "laps": 58,
        "results": [
            ("D-04", 2, 1, 25, "Finished"),
            ("D-03", 5, 2, 18, "Finished"),
            ("D-07", 3, 3, 15, "Finished"),
            ("D-08", 6, 4, 12, "Finished"),
            ("D-06", 7, 5, 10, "Finished"),
            ("D-09", 8, 6, 8, "Finished"),
            ("D-15", 9, 7, 6, "Finished"),
            ("D-10", 12, 8, 4, "Finished"),
            ("D-20", 10, 9, 2, "Finished"),
            ("D-19", 14, 10, 1, "Finished"),
            ("D-01", 1, 0, 0, "DNF"),
            ("D-05", 11, 0, 0, "DNF"),
        ],
    },
    {
        "raceId": "R-2024-04",
        "name": "Japanese Grand Prix",
        "circuit": "Suzuka International Racing Course",
        "country": "Japan",
        "date": "2024-04-07",
        "season": 2024,
        "round": 4,
        "laps": 53,
        "results": [
            ("D-01", 1, 1, 26, "Finished"),
            ("D-02", 2, 2, 18, "Finished"),
            ("D-04", 4, 3, 15, "Finished"),
            ("D-03", 3, 4, 12, "Finished"),
            ("D-07", 6, 5, 10, "Finished"),
            ("D-08", 7, 6, 8, "Finished"),
            ("D-06", 8, 7, 6, "Finished"),
            ("D-10", 9, 8, 4, "Finished"),
            ("D-09", 5, 9, 2, "Finished"),
            ("D-12", 11, 10, 1, "Finished"),
        ],
    },
]
