CREATE TABLE IF NOT EXISTS users (
  id        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  first_name      VARCHAR(100) NOT NULL,
  last_name       VARCHAR(100) NOT NULL,
  email           VARCHAR(255) UNIQUE NOT NULL,
  password     TEXT NOT NULL, 
  register_date     TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE users DROP COLUMN age;
ALTER TABLE users ADD COLUMN age VARCHAR(3);
ALTER TABLE users ALTER COLUMN age TYPE INTEGER USING age::integer;
ALTER TABLE users DROP COLUMN age;