
# Servicio BASE DE DATOS Postgres
services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # BACKEND API (Servidor que lee datos - Puerto 8000)
  backend:
    build: ./04_Backend
    pull_policy: build  # Fuerza a construir la imagen localmente en lugar de intentar descargarla
    container_name: backend
    ports:
      - "8000:8000" # Acceso: http://localhost:8000/docs
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=5)"]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 60s  

  # VISUALIZACION (Dash/Plotly - Puerto 8050)
  visualizacion:
    build: ./03_Visualizacion
    container_name: visualizacion
    ports:
      - "8050:8050" # Acceso: http://localhost:8050
    env_file: .env
    restart: unless-stopped

  # INGESTA
  ingesta:
    build: ./02_Ingesta
    container_name: ingesta
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy


volumes:
  postgres_data: