
# Servicio BASE DE DATOS Postgres
services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # BACKEND API (Servidor que lee datos - Puerto 8000)
  backend:
    build: ./04_Backend
    pull_policy: build  # Fuerza a construir la imagen localmente en lugar de intentar descargarla
    container_name: backend
    ports:
      - "8000:8000" # Acceso: http://localhost:8000/docs
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=5)"]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 60s  
    volumes:
      - images_data:/data/images
      
  # VISUALIZACION (Dash/Plotly - Puerto 8050)
  visualizacion:
    build: ./03_Visualizacion
    container_name: visualizacion
    ports:
      - "8050:8050" # Acceso: http://localhost:8050
    env_file: .env
    restart: unless-stopped

  # PGADMIN (Database Management - Puerto 5050)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80" # Acceso: http://localhost:5050
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json:ro
    entrypoint: >
      /bin/sh -c "
      mkdir -p /var/lib/pgadmin/storage/admin_admin.com;
      echo 'db:5432:tickets_db:postgres:${POSTGRES_PASSWORD}' > /var/lib/pgadmin/storage/admin_admin.com/pgpass;
      chmod 600 /var/lib/pgadmin/storage/admin_admin.com/pgpass;
      /entrypoint.sh
      "
    env_file:
      - .env

  # INGESTA
  ingesta:
    build: ./02_Ingesta
    container_name: ingesta
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy


volumes:
  postgres_data:
  images_data:
  pgadmin_data:
