CREATE TABLE IF NOT EXISTS users(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
password  TEXT NOT NULL, 
register_date TIMESTAMPTZ NOT NULL DEFAULT now()
);
