FROM confluentinc/cp-ksqldb-cli:latest

WORKDIR /scripts

COPY --chmod=755 entrypoint.sh .
RUN sed -i 's/\r$//' entrypoint.sh
COPY crear_stream.json .
COPY crear_tabla.json .

ENTRYPOINT ["./entrypoint.sh"]
